name: CI
on: [push, workflow_dispatch]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: âš™ï¸ Checkout code
        id: checkout
        uses: actions/checkout@v6

      - name: âœ¨ Markdownlint CLi2 Action
        if: steps.checkout.outcome == 'success' && !cancelled()
        uses: DavidAnson/markdownlint-cli2-action@v21
        with:
          globs: "**/*.md"
          config: .markdownlint-cli2.jsonc

      - name: âœ¨ Prettier Action
        if: steps.checkout.outcome == 'success' && !cancelled()
        uses: creyD/prettier_action@v4.6
        with:
          prettier_options: --config .prettierrc --check .
          dry: true

      - name: âœ¨ PSScriptAnalyzer Action
        if: steps.checkout.outcome == 'success' && !cancelled()
        uses: microsoft/psscriptanalyzer-action@v1.1
        with:
          path: ./src/PSNtfy # module root
          recurse: true
          settings: ./PSScriptAnalyzerSettings.psd1
          enableExit: true

  test-pwsh:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: pwsh

    steps:
      - name: âš™ï¸ Checkout code
        uses: actions/checkout@v6

      - name: ðŸŒŒ Get Run Metadata
        id: setup-meta
        uses: ./.github/actions/get-metadata

      - name: ðŸ¥“ Set PS7 Cache Path
        id: ps-cache
        run: |
          if ($IsWindows) {
            echo "CACHE_PATH=$(Join-Path $HOME 'Documents\PowerShell\Modules')" >> $env:GITHUB_OUTPUT
          } else {
            echo "CACHE_PATH=$HOME/.local/share/powershell/Modules" >> $env:GITHUB_OUTPUT
          }

      - name: ðŸ¥“ Cache PowerShell modules
        uses: actions/cache@v4
        with:
          path: ${{ steps.ps-cache.outputs.CACHE_PATH }}
          key: ${{ runner.os }}-pwsh-${{ hashFiles('**/requirements.psd1') }}
          restore-keys: |
            ${{ runner.os }}-pwsh-

      - name: ðŸ”» Bootstrap
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module -Name PSake -Scope CurrentUser -Confirm:$false
          Install-Module -Name Pester -MaximumVersion 5.7.1 -Confirm:$false

      - name: ðŸ§ª Run Pester
        id: tests
        run: Invoke-PSake Test-CI -NoLogo

      - name: ðŸ¥¨ Upload coverage report
        if: steps.tests.outcome != 'skipped' && !cancelled()
        uses: actions/upload-artifact@v5
        with:
          name: code-coverage_${{ runner.os }}-pwsh-${{ steps.setup-meta.outputs.short-sha }}-${{ steps.setup-meta.outputs.timestamp }}
          path: coverage.xml

      - name: ðŸ¥¨ Upload test results
        if: steps.tests.outcome != 'skipped' && !cancelled()
        uses: actions/upload-artifact@v5
        with:
          name: test-results_${{ runner.os }}-pwsh-${{ steps.setup-meta.outputs.short-sha }}-${{ steps.setup-meta.outputs.timestamp }}
          path: testResults.xml

      - name: ðŸ“œ Coverage Report to Codecov
        if: steps.tests.outcome != 'skipped' && !cancelled()
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          report_type: coverage
          fail_ci_if_error: true
          flags: pester
          disable_telem: true

      - name: ðŸ“œ Test Results to Codecov
        if: steps.tests.outcome != 'skipped' && !cancelled()
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          report_type: test_results
          fail_ci_if_error: true
          flags: pester
          disable_telem: true

  test-powershell:
    runs-on: windows-latest

    defaults:
      run:
        shell: powershell

    steps:
      - name: âš™ï¸ Checkout code
        uses: actions/checkout@v6

      - name: ðŸŒŒ Get Run Metadata
        id: setup-meta
        uses: ./.github/actions/get-metadata

      - name: ðŸ¥“ Set PS5 Cache Path
        id: ps-cache
        run: |
          echo "CACHE_PATH=$(Join-Path $HOME 'Documents\WindowsPowerShell\Modules')" >> $env:GITHUB_OUTPUT

      - name: ðŸ¥“ Cache PowerShell modules
        uses: actions/cache@v4
        with:
          path: ${{ steps.ps-cache.outputs.CACHE_PATH }}
          key: ${{ runner.os }}-powershell-${{ hashFiles('**/requirements.psd1') }}
          restore-keys: |
            ${{ runner.os }}-powershell-

      - name: ðŸ”» Bootstrap
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module -Name PSake -Scope CurrentUser -Confirm:$false
          Install-Module -Name Pester -MaximumVersion 5.7.1 -Confirm:$false

      - name: ðŸ§ª Run Pester
        id: tests
        run: Invoke-PSake Test-CI -NoLogo

      - name: ðŸ¥¨ Upload coverage report
        if: steps.tests.outcome != 'skipped' && !cancelled()
        uses: actions/upload-artifact@v5
        with:
          name: code-coverage_ps5-${{ steps.setup-meta.outputs.short-sha }}-${{ steps.setup-meta.outputs.timestamp }}
          path: coverage.xml

      - name: ðŸ¥¨ Upload test results
        if: steps.tests.outcome != 'skipped' && !cancelled()
        uses: actions/upload-artifact@v5
        with:
          name: test-results_ps5-${{ steps.setup-meta.outputs.short-sha }}-${{ steps.setup-meta.outputs.timestamp }}
          path: testResults.xml

      - name: ðŸ“œ Coverage Report to Codecov
        if: steps.tests.outcome != 'skipped' && !cancelled()
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          report_type: coverage
          fail_ci_if_error: true
          flags: pester
          disable_telem: true

      - name: ðŸ“œ Test Results to Codecov
        if: steps.tests.outcome != 'skipped' && !cancelled()
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          report_type: test_results
          fail_ci_if_error: true
          flags: pester
          disable_telem: true
