name: Test CI
on:
  push:
    paths:
      - ".github/workflows/test.yml" # this file
      - "src/**"
      - "psakefile.ps1"
  workflow_dispatch:

env:
  CovArtifact: code-coverage # for artifact naming consistency
  TestArtifact: test-results # for artifact naming consistency

jobs:
  test-pwsh:
    defaults:
      run:
        shell: pwsh
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: âš™ï¸ Check PS Version
        run: $PSVersionTable

      - name: âš™ï¸ Checkout code
        uses: actions/checkout@v6

      - name: ğŸŒŒ Get Run Metadata
        id: setup-meta
        uses: ./.github/actions/get-metadata

      - name: ğŸ¥“ Cache PowerShell modules
        uses: potatoqualitee/psmodulecache@v6.2.1
        with:
          modules-to-cache: psake, Pester:5.7.1, PSScriptAnalyzer:1.24.0
          shell: pwsh

      - name: ğŸ§ª Run Pester
        id: tests
        run: Invoke-PSake Test-CI -NoLogo

      - name: ğŸ¥¨ Upload Coverage Artifact
        if: steps.tests.outcome != 'skipped' && !cancelled()
        uses: actions/upload-artifact@v5
        with:
          name: ${{ env.CovArtifact }}_${{ runner.os }}-pwsh-${{ steps.setup-meta.outputs.short-sha }}-${{ steps.setup-meta.outputs.timestamp }}
          path: coverage.xml

      - name: ğŸ¥¨ Upload Test Results Artifact
        if: steps.tests.outcome != 'skipped' && !cancelled()
        uses: actions/upload-artifact@v5
        with:
          name: ${{ env.TestArtifact }}_${{ runner.os }}-pwsh-${{ steps.setup-meta.outputs.short-sha }}-${{ steps.setup-meta.outputs.timestamp }}
          path: testResults.xml

  test-powershell:
    runs-on: windows-latest
    defaults:
      run:
        shell: powershell

    steps:
      - name: âš™ï¸ Check PS Version
        run: $PSVersionTable

      - name: âš™ï¸ Checkout code
        uses: actions/checkout@v6

      - name: ğŸŒŒ Get Run Metadata
        id: setup-meta
        uses: ./.github/actions/get-metadata

      - name: ğŸ¥“ Cache PowerShell modules
        uses: potatoqualitee/psmodulecache@v6.2.1
        with:
          modules-to-cache: psake, Pester:5.7.1, PSScriptAnalyzer:1.24.0
          shell: powershell

      - name: ğŸ§ª Run Pester
        id: tests
        run: Invoke-PSake Test-CI -NoLogo

      - name: ğŸ¥¨ Upload Coverage Artifact
        if: steps.tests.outcome != 'skipped' && !cancelled()
        uses: actions/upload-artifact@v5
        with:
          name: ${{ env.CovArtifact }}_ps5-${{ steps.setup-meta.outputs.short-sha }}-${{ steps.setup-meta.outputs.timestamp }}
          path: coverage.xml

      - name: ğŸ¥¨ Upload Test Results Artifact
        if: steps.tests.outcome != 'skipped' && !cancelled()
        uses: actions/upload-artifact@v5
        with:
          name: ${{ env.TestArtifact }}_ps5-${{ steps.setup-meta.outputs.short-sha }}-${{ steps.setup-meta.outputs.timestamp }}
          path: testResults.xml

  codecov-upload:
    if: always()
    runs-on: ubuntu-latest
    needs: [test-pwsh, test-powershell]

    steps:
      - name: ğŸ“¥ Download Test artifacts
        uses: actions/download-artifact@v6
        id: test-artifacts
        with:
          path: test-artifacts
          pattern: ${{ env.TestArtifact }}_*
          merge-multiple: false

      - name: ğŸ“¥ Download Coverage artifacts
        uses: actions/download-artifact@v6
        id: coverage-artifacts
        with:
          path: coverage-artifacts
          pattern: ${{ env.CovArtifact }}_*
          merge-multiple: false

      - name: ğŸ“œ Upload Test Results to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          report_type: test_results
          fail_ci_if_error: true
          flags: pester
          disable_telem: true
          # All testResults.xml files
          directory: ${{ steps.test-artifacts.outputs.download-path }}

      - name: ğŸ“œ Upload Coverage Reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          report_type: coverage
          fail_ci_if_error: true
          flags: pester
          disable_telem: true
          # All coverage.xml files
          directory: ${{ steps.coverage-artifacts.outputs.download-path }}
